[SYSTEM]
name=Stage P-4 "Silver Sky"

[COMMENT]
Amidst the post-typhoon chaos, an accident has forced Tokyo International Airport to shut down all operations, requiring scores of flights to look elsewhere to land. In addition, wind forecasts show a potential runway change situation. Good luck.

[CLEARCONDITION]
Overall rank C or higher.
Arrival of designated aircraft

[CLEARRESULT]
Overall rank C or higher.
Arrival of diverting aircraft
Timely arrival of CAL17
Timely arrival of TBA270
;---
BGM 1: Frost Land
-> Zris
-
-