[SYSTEM]
name=Stage P-4 "Silver Sky"

[COMMENT]


[CLEARCONDITION]
Overall rank C or higher.
Arrival of designated aircraft

[CLEARRESULT]
Overall rank C or higher.
Arrival of diverting aircraft
Timely arrival of CAL17
Timely arrival of TBA270
;---
BGM 1: Frost Land
-> Zris
-
-